FROM node:16-alpine

ARG APP_PORT=3000
ARG NODE_ENV=production


ENV MONGO_HOST=$MONGO_HOST
ENV MONGO_PORT=$MONGO_PORT
ENV MONGO_USER=$MONGO_USER
ENV MONGO_PASS=$MONGO_PASS  
ENV MONGO_DB=$MONGO_DB
ENV NODE_ENV=${NODE_ENV}
ENV APP_PORT=${APP_PORT}
ENV POKEMON_DATA_URL=$POKEMON_DATA_URL


WORKDIR /src

COPY ./package.json ./package-lock.json ./
RUN npm install

COPY ./ .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main.js"]