FROM node:16-alpine

ARG APP_PORT
ARG MONGO_HOST
ARG POKEMON_DATA_URL
ARG MONGO_PORT
ARG MONGO_USER
ARG MONGO_PASS
ARG MONGO_DB
ENV MONGO_HOST=$MONGO_HOST
ENV MONGO_PORT=$MONGO_PORT
ENV MONGO_USER=$MONGO_USER
ENV MONGO_PASS=$MONGO_PASS  
ENV MONGO_DB=$MONGO_DB
ENV NODE_ENV=development
ENV APP_PORT=3000
ENV POKEMON_DATA_URL=$POKEMON_DATA_URL



WORKDIR /src

COPY ./package.json ./package-lock.json ./
RUN npm install

COPY ./ .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main.js"]